# Intro to Numpy

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating Arrays

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [15]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [18]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [ ]:
# similar to range() in python
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-Dimensional Arrays

In [5]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [12]:
n[0][1]

np.int64(2)

In [14]:
n[0][1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
n[0]

array([ 1, 20,  3])

In [21]:
n[2] = [1,1,1]

In [23]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [25]:
# get all rows but only the second column at index = 1
n[:, 1]

array([20,  5,  1])

In [28]:
n[:, 2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Random Generated Arrays

In [ ]:
# uniform distribution and seed. rand is only psuedo random
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [32]:
# normal distribution and seed. randn is only psuedo random
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [34]:
# psuedo random integers. between 0 and 99 with 5 rows and 2 columns.a
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise Operations

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
# basically any math operation can be completed with numpy arrays
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

## Comparision Operations

In [42]:
a

array([0, 1, 2, 3, 4])

In [43]:
a > 2

array([False, False, False,  True,  True])

In [44]:
a > b

array([False, False,  True,  True,  True])

In [46]:
# return all the elements for wich this condition a > 2 is true in a.
a[a > b]

array([2, 3, 4])

## Summarizing Operations

In [48]:
a

array([0, 1, 2, 3, 4])

In [49]:
a.max()

np.int64(4)

In [50]:
a.min()

np.int64(0)

In [51]:
a.mean()

np.float64(2.0)

In [52]:
a.std()

np.float64(1.4142135623730951)