# Linear Algebra Refresher

- Vector operations
- Multiplication
  - Vector-vector multiplication
  - Matrix-vector multiplication
  - Matrix-matrix multiplication
- Identity matrix
- Inverse

# Vector Operations

In [2]:
import numpy as np

In [3]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [5]:
# addition 
u + v

array([ 5, 11, 13, 12])

In [7]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [8]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

## Mulitplication

In [ ]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [13]:
vector_vector_multiplication(u, v)

np.float64(110.0)

In [14]:
# In Python an implemenation of the function above already exists. dot()
u.dot(v)

np.int64(110)

## Matrix-vector multiplication

In [15]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [17]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [ ]:
# 3 rows and 4 columns. For matrix vector math to work the number of columns needs to match. U.shape[1] is the number of columns in the matrix.
U.shape

(3, 4)

In [26]:
# While v.shape[0] would be the number of columns for the vector
v.shape

(4,)

In [20]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [27]:
matrix_vector_multiplication(U, v)

array([98., 31., 35.])

In [ ]:
# dot() also allows for vector * matrix multiplication
U.dot(v)

array([98, 31, 35])

## Matrix-Matrix Multiplication

In [39]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0]
])

In [40]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [41]:
V.shape

(4, 3)

In [33]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [42]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [44]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

An identity matrix is a square matrix where all the elements on the main diagonal are 1, and all other elements are 0.

In [ ]:
# 3 column identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [ ]:
# like mulitplying a scalar by 1 when you multiply a matrix by an identity matrix you get the matrix back.
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse Matrix

In [52]:
# Vs (V square for square matrix)
Vs = V[[0,1,2]]

In [53]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [ ]:
# shhould give back a square matrix!
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])